name: Build Wheels

on: [push]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: python -m pip install -r requirements.txt

    - name: Build and test wheels
      run: python -m cibuildwheel --platform linux --output-dir wheelhouse
      env:
        CIBW_BEFORE_TEST: |
          python -m pip install pytest
          python -m pip install $(ls /tmp/cibuildwheel/repaired_wheel/*.whl)
        CIBW_TEST_COMMAND: "python -m pytest {project}"
