name: CI Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build wheels
        run: |
          pip install cibuildwheel
          cibuildwheel --output-dir dist/
      - name: Test with Pytest
        run: pytest
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*
