name: Build Wheels

on:
  push:
    branches:
      - main
      - master
      - serialization

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    if: github.repository_owner == 'rleap-project'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies and requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install setuptools wheel twine cibuildwheel

    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here:
        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
        boost_version: 1.80.0

    - name: Build wheels
      run: cibuildwheel --platform linux --output-dir wheelhouse
      env:
        CIBW_BUILD_VERBOSITY: "1"
        CIBW_ENVIRONMENT_LINUX: BOOST_ROOT='${{ steps.install-boost.outputs.BOOST_ROOT }}'

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ wheelhouse/*
